### ISSUE TITLE
Why the memory of weights is 1.6G?

### ISSUE THREAD

**Issue by JackieLeeTHU11** [MarvinTeichmann/tensorflow-fcn#15]
@MarvinTeichmann 
When I save the weights of this model (FCN), the memory is 1.6GB and the .meta file is 537.7MB. But actually, the memory of the weights is about 530MB. It sames strange here?

**Comment by MarvinTeichmann** [comment]
The reason is, that tensorflow stores weights much more inefficient then numpy. If you care for memory store the weights in an .npy file.

Alternatively discuss the issue with a tensorflow maintainer (e.g.  @vrv), if you think this should be fixed.
