### ISSUE TITLE
Problems with gray images

### ISSUE THREAD

**Issue by jiao0805** [MarvinTeichmann/tensorflow-fcn#24]
Hi Mr.Marvin Teichmann
I found this in the usage that:
The images is a tensor with shape [None, h, w, 3]. Where h and w can have arbitrary size.

My training data is gray images with no rgb channels.
Can I still use this code and vgg to train them?

**Comment by MarvinTeichmann** [comment]
Yes, you can. Make sure that you load or convert the image as 3 channel tensor, e.g. by calling `scipy.misc.imread(image_file, mode='RGB')`. The input producer of [KittiSeg](https://github.com/MarvinTeichmann/KittiSeg/blob/master/inputs/kitti_seg_input.py) works out of the box with this code for greyscale images.

**Comment by jiao0805** [comment]
Thanks a lot for your help！ ^-^
