### ISSUE TITLE
ouput image doesn't make sense

### ISSUE THREAD

**Issue by aleksandrmelnyk** [MarvinTeichmann/tensorflow-fcn#33]
Seems like annotations on output image doesn't correspond input one...? After run test_fcn32_vgg.py I got:

![tabby_cat](https://user-images.githubusercontent.com/930971/27514772-ed21fd0a-599c-11e7-9620-54009fbdff64.png)
![fcn32_upsampled](https://user-images.githubusercontent.com/930971/27514777-fde17922-599c-11e7-8d69-2983d6e84611.png)

**Comment by MarvinTeichmann** [comment]
The model is not trained. The weights are just initialized from classification finetuning. Train the model to get better results.
