### ISSUE TITLE
training dataset

### ISSUE THREAD

**Issue by weiliu620** [MarvinTeichmann/tensorflow-fcn#6]
After reading the readme file, it's still not clear to me what data set was used for training? I understand some filters are initialized from vgg16, then training is done on what dataset?

By "No Pascal VOC finetuning was applied to the weights.", I guess the training set is not Pascal VOC? 

Thanks,

**Comment by MarvinTeichmann** [comment]
Vgg16 is trained on ImageNet. No further training was performed. The model is meant to be a good start to do FineTuning on your own data.

**Comment by weiliu620** [comment]
Great. Thanks for the reply. Would be good to see such information on readme file.

**Comment by MarvinTeichmann** [comment]
The Readme currently says: 

> No Pascal VOC finetuning was applied to the weights. The model is meant to be finetuned on your own data.

Isn't this a clear statement?
